name: hourly-cron-job
on:
  schedule:
    - cron: '* */1 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call fn
        run: |
          curl --request POST \
          --url '${{ secrets.API_URL }}' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'